title: Personal Notes - Source's Website
name: SourceWang
email: 1154722015@qq.com
description: SourceWang's Website - Persional blog
keywords: wangziyuan
skill_software_keywords: [Java, C, Python, Design Patterns]
skill_web_keywords: [HTML, CSS, Javascript, jQuery, PHP, Boostrap]
skill_mobile_app_keywords: [Android, MUI]

timezone: PRC
encoding: "utf-8"

# url: http://sourcewang.github.io/AAA
url: http://sourcew16.com
baseurl:  "/"
domain:
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/SourceWang/sourcewang.github.io/

# Build settings
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  - jekyll-html-pipeline
  - jekyll-paginate

analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /footprint
    label: Footprint

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

popular_repos: ['sourcewang.github.io', 'mfz']
contribute_repos: ['SourceWang/sourcewang.github.io', 'SourceWang/mfz']
